apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubedep
spec:
  selector:
    matchLabels: 
      app: youtubepod
  template:
    metadata:
      name: youtubepod
      labels:
        app: youtubepod
    spec:
      containers:
      - name: youtubeapp
        image: kesav38/youtubecicd:Newtag
        ports:
        - containerPort: 3000 # Your Node.js application should listen on port 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: youtubesvc
spec:
  type: LoadBalancer
  selector:
    app: youtubepod
  ports:
  - port: 80  # You can use port 80 here for HTTP traffic
    targetPort: 3000 # This should match the port your Node.js application is running on (3000)
      
